version: '3.7'
services:
  #######################
  #### WEB-API
  #######################
  webapi:
    container_name: webapi
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/webapi
    ports:
      - 3333:3333
    expose:
      - 3333
