version: '3.7'
services:
  #######################
  #### WEB-API
  #######################
  webapi:
    container_name: webapi
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/webapi
    env_file:
      - ./development.env
    ports:
      - 3333:3333
    expose:
      - 3333
    links:
      - db

  db:
    image: postgres:12.1
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: cartao_alianca_dev
    ports: ['5432:5432']
    expose: ['5432']
